<?php
/**
 * Copyright © Magecan, Inc. All rights reserved.
 */
$brands = $block->getBrandOptions();

$enable = $block->getEnable();
$infinite = $block->getInfinite();
$autoplay = $block->getAutoplay();
$autoplaySpeed = $block->getAutoplaySpeed();
$arrows = $block->getArrows();
$dots = $block->getDots();
?>

<?php if (!empty($brands)): ?>
<div class="brand-slider">
    <div class="brand-slider-container">
        <div class="brand-slider-wrapper">
            <?php foreach ($brands as $brand): ?>
                <li class="brand-slide">
                    <a href="brand/index/view?brand=<?= $brand['label'] ?>" style="display: flex; flex-direction: column; align-items: center; justify-content: center; text-decoration: none;">
                        <img src="<?= $brand['image'] ?>">
                        <h3><?= $brand['label'] ?></h3>
                    </a>
                </li>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php else: ?>
    <p>No brands available.</p>
<?php endif; ?>

<script>
require(['jquery', 'slick'], function ($) {
    $(document).ready(function () {
        $('.brand-slider-wrapper').slick({
            infinite: <?= $infinite ? 'true' : 'false' ?>,
            autoplay: <?= $autoplay ? 'true' : 'false' ?>,
            autoplaySpeed: <?= $autoplaySpeed ?>,
            arrows: <?= $arrows ? 'true' : 'false' ?>,
            dots: <?= $dots ? 'true' : 'false' ?>,
            slidesToScroll: 1,
            slidesToShow: 6, 

            responsive: [
                {
                  breakpoint: 1024,
                  settings: {
                    slidesToShow: 5
                  }
                },
                {
                  breakpoint: 600,
                  settings: {
                    slidesToShow: 4
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 3
                  }
                }
              ]
        });
    });
});
</script>
